export {default as AboutMe} from './AboutMe'
export {default as Home} from './Home'
export {default as MyWork} from './MyWork'
export {default as NavBar} from './NavBar'
export {default as Services} from './Services'
export {default as Skills} from './Skills'
export {default as SocialMedia} from './SocialMedia'
